# Generated by Django 3.2.5 on 2021-07-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_date_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_add',
        ),
    ]
