# Generated by Django 3.2.5 on 2021-07-28 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
